import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <nav>
          <ul>
            <li><Link href="/">Accueil</Link></li>
            <li><Link href="/discographie">Discographie</Link></li>
            <li><Link href="/concerts">Concerts</Link></li>
            <li><Link href="/spectacles">Spectacles</Link></li>
            <li><Link href="/biographie">Biographie</Link></li>
            <li><Link href="/instruments">Instruments</Link></li>
            <li><Link href="/voix">Voix</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
